import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const solaimanLipi = localFont({
  src: [
    {
      path: "/asset/font/SolaimanLipi_22-02-2012.ttf",
      weight: "400",
    },
    {
      path: "/asset/font/SolaimanLipi_Bold_10-03-12.ttf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "CHTVENGUARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${solaimanLipi.className}`}>{children}</body>
    </html>
  );
}
