import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Appbar from "@/components/shared/Appbar";
import { ThemeProvider } from "next-themes";

const solaimanLipi = localFont({
  src: [
    {
      path: "/asset/font/SolaimanLipi_22-02-2012.ttf",
      weight: "400",
    },
    {
      path: "/asset/font/SolaimanLipi_Bold_10-03-12.ttf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "CHTVENGUARD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${solaimanLipi.className} font-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange={false}
          storageKey="chtvenguard-theme"
        >
          <div className="min-h-screen bg-background text-foreground">
            <Appbar />
            <main className="pt-16">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
